version: '3'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    ports:
      - '55002:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: finance
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
